import json
from pathlib import Path
from typing import Optional
from backend.app.schemas.api_models import AnalyzeResponse


class ReportService:
    """Renders downloadable reports (PDF and JSON) with full content parity."""

    def render_json(self, response: AnalyzeResponse) -> str:
        return response.model_dump_json(by_alias=True, indent=2)

    def render_html_report(self, response: AnalyzeResponse) -> str:
        """Generates clean, printable HTML report with complete content parity."""
        trace_rows = "".join([
            f"""<tr>
                <td style="padding: 6px 10px; border: 1px solid #ddd;">{s.step_index}</td>
                <td style="padding: 6px 10px; border: 1px solid #ddd;"><strong>{s.component}</strong></td>
                <td style="padding: 6px 10px; border: 1px solid #ddd;">{s.adapter_id_or_version or 'N/A'}</td>
                <td style="padding: 6px 10px; border: 1px solid #ddd;">{s.wall_clock_ms} ms</td>
                <td style="padding: 6px 10px; border: 1px solid #ddd;">{s.output_summary}</td>
            </tr>"""
            for s in response.execution_trace.steps
        ])

        boxes_count = len(response.evidence.boxes)
        tags_count = len(response.evidence.region_tags or [])

        html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SatQuery AI Analysis Report - {response.session_id}</title>
    <style>
        body {{ font-family: 'Helvetica Neue', Arial, sans-serif; color: #1e293b; line-height: 1.5; padding: 30px; }}
        h1, h2, h3 {{ color: #0f172a; margin-top: 0; }}
        .badge {{ display: inline-block; padding: 4px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
        .badge-high {{ background: #dcfce7; color: #15803d; }}
        .badge-med {{ background: #fef3c7; color: #b45309; }}
        .badge-low {{ background: #ffe4e6; color: #be123c; }}
        .card {{ background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin-bottom: 20px; }}
        table {{ width: 100%; border-collapse: collapse; font-size: 12px; }}
        th {{ background: #f1f5f9; text-align: left; padding: 8px 10px; border: 1px solid #cbd5e1; }}
    </style>
</head>
<body>
    <div style="border-bottom: 2px solid #0284c7; padding-bottom: 12px; margin-bottom: 20px;">
        <h2>SatQuery AI — Remote Sensing Analysis Report</h2>
        <p style="color: #64748b; font-size: 12px; margin: 0;">
            SIH26167 • Indian Space Research Organisation (ISRO) | Session ID: <strong>{response.session_id}</strong>
        </p>
    </div>

    <div class="card">
        <h3>1. Executive Grounded Answer</h3>
        <p style="font-size: 14px; line-height: 1.6;">{response.answer_text or 'Analysis terminated with physical rejection.'}</p>
        <div>
            <strong>Confidence Tier:</strong> 
            <span class="badge badge-high">{response.confidence.tier} CONFIDENCE</span>
            <p style="font-size: 12px; color: #475569; margin: 6px 0 0;">Rationale: {response.confidence.rationale}</p>
        </div>
    </div>

    <div class="card">
        <h3>2. Evidence Summary</h3>
        <p style="font-size: 12px; color: #475569;">
            Detected Features: <strong>{boxes_count} Bounding Boxes</strong> | 
            Complementarity Tags: <strong>{tags_count} Multi-Sensor Regions</strong>
        </p>
    </div>

    <div class="card">
        <h3>3. Auditable Execution Trace</h3>
        <table>
            <thead>
                <tr>
                    <th>Step</th>
                    <th>Component</th>
                    <th>Adapter</th>
                    <th>Duration</th>
                    <th>Output Summary</th>
                </tr>
            </thead>
            <tbody>
                {trace_rows}
            </tbody>
        </table>
    </div>

    <div style="font-size: 11px; color: #94a3b8; text-align: center; margin-top: 30px;">
        Generated by SatQuery AI Engine • GeoGraphRAG Precondition Enforced • Verifier-in-the-Loop
    </div>
</body>
</html>"""
        return html


report_service = ReportService()
